# SALE
LEN_MAX_MERCHANT_ORDER_ID = 50
LEN_MAX_CUSTOMER_NAME = 255
REGEX_MERCHANT_ORDER_ID = "^[0-9]+$"
# CARD
LEN_MAX_SECURITY_CODE = 4
LEN_MAX_EXPIRATION_DATE = 7
REGEX_EXPIRATION_DATE = r'\d{2}/\d{4}'
LEN_MIN_HOLDER = 1
# PAYMENT
MAX_AMOUNT = 10**15
MIN_AMOUNT = 0
LEN_MAX_TYPE = 100
MAX_INSTALLMENTS = 10**12
MIN_INSTALLMENTS = 0
# BANKSLIP
LEN_MAX__ADRESS_STREET = 255
LEN_MAX_ADRESS_NUMBER = 15
LEN_MAX_ADRESS_ZIP_CODE = 9
LEN_MAX_ADRESS_DISTRICT = 50
LEN_MAX_ADRESS_CITY = 50
LEN_MAX_ADRESS_STATE = 2
LEN_MAX_ADRESS_COUNTRY = 35
LEN_MAX_PROVIDER = 15
LEN_MAX_IDENTIFICATION = 14
LEN_MAX_INSTRUCTIONS = 255
